version: "3.9"  # optional since v1.27.0
services:
  web:
    build:
      context: .
      dockerfile: ./server/server.DockerFile
    ports:
      - "3000:3000"
      - "65000:65000"
    depends_on:
     - worker
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  worker:
    build:
      context: .
      dockerfile: ./server/worker.DockerFile
    container_name: worker
    ports:
      - "65001:65001"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1